### ISSUE TITLE
Multiplayer farmhands not seeing slimehutch interior

### ISSUE THREAD

**Issue by lauren-mods** [lauren-mods/StardewMods#13]
https://www.nexusmods.com/stardewvalley/mods/6497/?tab=posts&BH=2

**Comment by lauren-mods** [comment]
Log shared on nexus:
https://smapi.io/log/da65322289b5403fba8acd903ddd334b

Mod crashed when loading asset 'Maps/SlimeHutch' (for the 'Slime Hutch to Menagerie' content pack). SMAPI will use the default asset instead. Error details:SContentLoadException: Slime Hutch to Menagerie loaded map 'assets/largeSlimeHutch.tbin' with invalid tilesheet path 'z_seasonsindoors.png'. The tilesheet couldn't be found relative to either map file or the game's content folder.
at StardewModdingAPI.Framework.ContentManagers.ModContentManager.FixTilesheetPaths(Map map, String relativeMapPath, Boolean fixEagerPathPrefixes) in SMAPI\Framework\ContentManagers\ModContentManager.cs:line 450
at StardewModdingAPI.Framework.ContentManagers.ModContentManager.LoadMapFile[T](IAssetName assetName, FileInfo file) in SMAPI\Framework\ContentManagers\ModContentManager.cs:line 296
at StardewModdingAPI.Framework.ContentManagers.ModContentManager.LoadExact[T](IAssetName assetName, Boolean useCache) in SMAPI\Framework\ContentManagers\ModContentManager.cs:line 131
at StardewModdingAPI.Framework.ModHelpers.ModContentHelper.Load[T](String relativePath) in SMAPI\Framework\ModHelpers\ModContentHelper.cs:line 57
at ContentPatcher.Framework.Patches.LoadPatch.Load[T](IAssetName assetName) in E:\source\_Stardew\Mods.Pathoschild\ContentPatcher\Framework\Patches\LoadPatch.cs:line 42
at ContentPatcher.Framework.PatchManager.ApplyLoad[T](IPatch patch, IAssetName assetName) in E:\source\_Stardew\Mods.Pathoschild\ContentPatcher\Framework\PatchManager.cs:line 519
at ContentPatcher.Framework.PatchManager.<>c__DisplayClass24_0`1.<ApplyPatchesToAsset>b__0() in E:\source\_Stardew\Mods.Pathoschild\ContentPatcher\Framework\PatchManager.cs:line 472
at StardewModdingAPI.Events.AssetRequestedEventArgs.<>c__DisplayClass17_0.<LoadFrom>b__0(IAssetInfo _) in SMAPI\Events\AssetRequestedEventArgs.cs:line 84
at StardewModdingAPI.Framework.ContentManagers.GameContentManager.ApplyLoader[T](IAssetInfo info, List`1 loadOperations) in SMAPI\Framework\ContentManagers\GameContentManager.cs:line 195
